Correlation = 
VAR AvgX = AVERAGE('correlationDataX'[valueX])
VAR AvgY = CALCULATE(AVERAGE('correlationDataY'[valueY]), TREATAS(VALUES('correlationDataX'[areaAltLabel]), 'correlationDataY'[areaAltLabel]))
VAR CovXY = SUMX(
    'correlationDataX',
    ('correlationDataX'[valueX] - AvgX) * 
    (CALCULATE(AVERAGE('correlationDataY'[valueY]), TREATAS(VALUES('correlationDataX'[areaAltLabel]), 'correlationDataY'[areaAltLabel])) - AvgY)
)
VAR VX = SUMX('correlationDataX', ('correlationDataX'[valueX] - AvgX) * ('correlationDataX'[valueX] - AvgX))
VAR VY = SUMX(
    'correlationDataY',
    ('correlationDataY'[valueY] - AvgY) * ('correlationDataY'[valueY] - AvgY)
)
VAR Corr = DIVIDE(CovXY, SQRT(VX * VY))
RETURN IF(ISBLANK(Corr),"N/A",Corr)
