R² Value = 
VAR AvgX = AVERAGE('correlationDataX'[valueX])
VAR AvgY = CALCULATE(AVERAGE('correlationDataY'[valueY]), TREATAS(VALUES('correlationDataX'[areaAltLabel]), 'correlationDataY'[areaAltLabel]))
VAR SSxy = SUMX(
    'correlationDataX',
    ('correlationDataX'[valueX] - AvgX) * (CALCULATE(AVERAGE('correlationDataY'[valueY]), TREATAS(VALUES('correlationDataX'[areaAltLabel]), 'correlationDataY'[areaAltLabel])) - AvgY)
)
VAR SSxx = SUMX('correlationDataX', ('correlationDataX'[valueX] - AvgX) * ('correlationDataX'[valueX] - AvgX))
VAR SSyy = SUMX(
    'correlationDataY',
    ('correlationDataY'[valueY] - AvgY) * ('correlationDataY'[valueY] - AvgY)
)
VAR R_Squared = DIVIDE(SSxy^2, SSxx * SSyy)
RETURN IF(ISBLANK(R_Squared),"N/A",R_Squared)
